name: Publish requirements with StrictDoc

on:
  push:
    branches:
      - main
    paths:
      - 'docs/requirements/strictdoc/**/*.*'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install StrictDoc
        run: pip install strictdoc

      - name: Generate StrictDoc HTML
        run: |
          strictdoc export \
            docs/requirements/strictdoc \
            --output-dir public

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: public

  deploy:
    needs: build

    runs-on: ubuntu-latest

    environment:
      name: github-pages

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5